### ISSUE TITLE
确实很不错

### ISSUE THREAD

**Issue by PerfectShen** [tbl00c/ZZUIHelper#1]
只是不习惯用这个 适合 无聊的时候玩玩  对于有些习惯敲代码的人 他们都是拒绝用鼠标点的。
不过这个 确实很好用 ！给你个 star

**Comment by tbl00c** [comment]
这个就是尝试解决那些坚守手写UI的项目中，有的人想点点点的矛盾，xib/sb这种开发效率会高很多。

**Comment by PerfectShen** [comment]
但是有些人是顽固不化的人   大多数程序员也是这样的- 而且 他们可能宁愿手写 masonry ，至少目前 我是这个样子的
